### ISSUE TITLE
Avg aggregation

### ISSUE THREAD

**Issue by realvictorprm** [lambdaworks/zio-elasticsearch#244]
Maybe I oversee something here but I could not find a possibility to use the average aggregation. If they want to be added they should appear [here](https://github.com/lambdaworks/zio-elasticsearch/blob/29eda304c902fa314e7b50676f68f0dba537daf8/modules/library/src/main/scala/zio/elasticsearch/ElasticAggregation.scala) probably, right?

**Comment by drmarjanovic** [comment]
Hi, @realvictorprm, thank you for your comment. You are absolutely right - we don't have `avgAggregation` supported yet. However, you can check the #118 issue, where both the list of unsupported aggregations is listed as well as hints on how it should be implemented in a way you are willing to contribute 😇 

I'm closing this issue in favor of #118.
