### ISSUE TITLE
How to do an Index Pattern search/lookup

### ISSUE THREAD

**Issue by ianlintner** [lambdaworks/zio-elasticsearch#310]
Can you help me figure out how to use index patterns with zio-elasticsearch?

Elastic Search Index Pattern Search 
```
GET categories*/_search
{
  "query": {
    "match_all": {}
  }
}
```

Intuitively I tried something like this
```scala
elasticSearch.execute(getById(IndexName("categories*"),DocumentId("documentId")))
```

This is blocked because IndexName does not allow "*".

I have indexes: categories_1, categories_2, categories_i+1

**Comment by drmarjanovic** [comment]
Hi, @ianlintner! 

Thanks for pointing that out! 

Unfortunately, it's not supported at the moment.

However, we are going to think about this and resolve it as fast as possible.

**Comment by dbulaja98** [comment]
Hello @ianlintner!

This issue is resolved now, feel free to try it and ask if you need any help.
