### ISSUE TITLE
JVM 8 support

### ISSUE THREAD

**Issue by dbulaja98** [lambdaworks/zio-elasticsearch#59]
### Description:

The current version of the `sttp` does not support JVM 8. 

Currently we use latest version of sttp for zio2.
`"com.softwaremill.sttp.client3" %% "zio" % "3.8.3"`

We have following issue with
`sttp/client3/SttpBackend has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`, which means it is not compatible with JRE 8.

For compatibility we can use some earlier version of `sttp` which can be found here: https://github.com/softwaremill/sttp/releases

**Comment by mijicd** [comment]
Two things:
- this is not the latest sttp release
- downgrading it won't fix your issue


The main problem here is that you're using a backend built on top of HttpClient that comes with Java 11. Choosing an alternative backend (or providing an interior) will resolve your issue without the need to downgrade dependencies.

**Comment by drmarjanovic** [comment]
At the moment we don't need Java 8 support, so I'm closing this right now.
