### ISSUE TITLE
Replace WireMock with STTP

### ISSUE THREAD

**Issue by drmarjanovic** [lambdaworks/zio-elasticsearch#87]
### Description

Replace the current implementation of WireMock with STTP. You can refer to the documentation [here](https://sttp.softwaremill.com/en/latest/testing.html).

WireMock is used to confirm that HttpElasticExecutor is creating and executing expected HTTP requests.

**Comment by kevchuang** [comment]
I'm interested to work on this one

**Comment by drmarjanovic** [comment]
All yours! 🎉

**Comment by drmarjanovic** [comment]
@kevchuang, any news here? 😄 Thanks in advance. 🙏🏻

**Comment by kevchuang** [comment]
Hey @drmarjanovic ! Sorry I was a bit busy these past weeks, I'm gonna work on it next week 😄

**Comment by drmarjanovic** [comment]
Thanks! 🙏🏻  No problem! We are looking forward to your PRs! 🤩
